### ISSUE TITLE
Using debian-unstable-opam on Travis

### ISSUE THREAD

**Issue by lindig** [ocaml/ocaml-ci-scripts#272]
It is not obvious how to use `debian-unstable-opam` (and probably more distros) because the docker image does not initialize the Opam environment and this leads to failure. So far I have tried:

```
language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - OCAML_VERSION="4.07"
    - PACKAGE=xenstored
    - PINS="xen:. xenstored:."
  matrix:
    - DISTRO="debian-unstable-opam"
```

This leads to:

```
[ERROR] Opam has not been initialised, please run `opam init'
The command '/bin/sh -c opam update' returned a non-zero code: 50
The command "bash -ex .travis-docker.sh" exited with 50.
```
This could very well be a matter of documentation.
